//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRestaurantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuLeft
    {
        public int Id { get; set; }
        public string MenuName { get; set; }
        public int ParentId { get; set; }
        public bool Locked { get; set; }
    }
}
