//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRestaurantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFile
    {
        public int UploadFileId { get; set; }
        public string UploadFileName { get; set; }
        public string UploadFilePath { get; set; }
        public string UploadFileVersion { get; set; }
        public Nullable<int> SubCatagoryId { get; set; }
        public byte[] UploadFileImage { get; set; }
    }
}
